@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri Jun 26 18:57:03 +0200 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 89ea1252dd9d4a7c8cae1839e9df8d51 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_pwm_spi_behav xil_defaultlib.tb_pwm_spi -log elaborate.log"
call xelab  -wto 89ea1252dd9d4a7c8cae1839e9df8d51 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_pwm_spi_behav xil_defaultlib.tb_pwm_spi -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
